apiVersion: apps/v1
kind: Deployment
metadata:
  name: altershield-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altershield
  template:
    metadata:
      labels:
        app: altershield
    spec:
      containers:
        - name: altershield
          image: codefriday123/altershield:1.0-dev-0.1.6
          ports:
            - containerPort: 8080